AmCharts.makeChart("chartdiv1",
				{
					"type": "serial",
					"categoryField": "category",
					"rotate": true,
					"angle": 30,
					"depth3D": 30,
					"sequencedAnimation": false,
					"startDuration": 0.3,
					"startEffect": "elastic",
					"accessibleTitle": "",
					"handDrawThickness": 0,
					"theme": "light",
					"categoryAxis": {
						"gridPosition": "start"
					},
					"trendLines": [],
					"graphs": [
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-1",
							"title": "Andaman and Nicobar Islands",
							"type": "column",
							"valueField": "Andaman and Nicobar Islands"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-2",
							"title": "Andhra Pradesh",
							"type": "column",
							"valueField": "Andhra Pradesh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-3",
							"title": "Arunachal Pradesh",
							"type": "column",
							"valueField": "Arunachal Pradesh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-4",
							"title": "Assam",
							"type": "column",
							"valueField": "Assam"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-5",
							"title": "Bihar",
							"type": "column",
							"valueField": "Bihar"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-6",
							"title": "Chandigarh",
							"type": "column",
							"valueField": "Chandigarh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-7",
							"title": "Chhattisgarh",
							"type": "column",
							"valueField": "Chhattisgarh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-8",
							"title": "Dadra and Nagar Haveli",
							"type": "column",
							"valueField": "Dadra and Nagar Haveli"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-9",
							"title": "Daman and Diu",
							"type": "column",
							"valueField": "Daman and Diu"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-10",
							"title": "Delhi",
							"type": "column",
							"valueField": "West Bengal"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-11",
							"title": "Goa",
							"type": "column",
							"valueField": "Goa"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-12",
							"title": "Gujarat",
							"type": "column",
							"valueField": "Gujarat"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-13",
							"title": "Haryana",
							"type": "column",
							"valueField": "Haryana"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-14",
							"title": "Himachal Pradesh",
							"type": "column",
							"valueField": "Himachal Pradesh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-15",
							"title": "Jammu and Kashmir",
							"type": "column",
							"valueField": "Jammu and Kashmir"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-16",
							"title": "Jharkhand",
							"type": "column",
							"valueField": "Jharkhand"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-17",
							"title": "Karnataka",
							"type": "column",
							"valueField": "Karnataka"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-18",
							"title": "Kerala",
							"type": "column",
							"valueField": "Kerala"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-19",
							"title": "Lakshadweep",
							"type": "column",
							"valueField": "Lakshadweep"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-20",
							"title": "Madhya Pradesh",
							"type": "column",
							"valueField": "Madhya Pradesh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-21",
							"title": "Maharashtra",
							"type": "column",
							"valueField": "Maharashtra"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-22",
							"title": "Manipur",
							"type": "column",
							"valueField": "Manipur"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-23",
							"title": "Meghalayah",
							"type": "column",
							"valueField": "Meghalayah"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-24",
							"title": "Mizoram",
							"type": "column",
							"valueField": "West Bengal"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-25",
							"title": "Nagaland",
							"type": "column",
							"valueField": "Nagaland"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-26",
							"title": "Orissa",
							"type": "column",
							"valueField": "Orissa"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-27",
							"title": "Pondicherry",
							"type": "column",
							"valueField": "Pondicherry"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-28",
							"title": "Punjab",
							"type": "column",
							"valueField": "Punjab"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-29",
							"title": "Rajasthan",
							"type": "column",
							"valueField": "Rajasthan"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-30",
							"title": "Sikkim",
							"type": "column",
							"valueField": "Sikkim"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-31",
							"title": "Tamil Nadu",
							"type": "column",
							"valueField": "Tamil Nadu"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-32",
							"title": "Telangana",
							"type": "column",
							"valueField": "Telangana"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-33",
							"title": "Tripura",
							"type": "column",
							"valueField": "Tripura"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-34",
							"title": "Uttar Pradesh",
							"type": "column",
							"valueField": "Uttar Pradesh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-35",
							"title": "Uttarakhand",
							"type": "column",
							"valueField": "Uttarakhand"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-36",
							"title": "West Bengal",
							"type": "column",
							"valueField": "West Bengal"
						}
					],
					"guides": [],
					"valueAxes": [
						{
							"id": "ValueAxis-1",
							"stackType": "regular",
							"title": ""
						}
					],
					"allLabels": [
						{
							"id": "Label-1"
						}
					],
					"balloon": {},
					"legend": {
						"enabled": true,
						"useGraphSettings": true
					},
					"titles": [
						{
							"id": "Title-1",
							"size": 15,
							"text": ""
						}
					],
					"dataProvider": [
						{
							"category": "January",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": null,
							"Assam": null,
							"Bihar": null,
							"Chandigarh": null,
							"Chhattisgarh": null,
							"Dadra and Nagar Haveli": null,
							"Daman and Diu": null,
							"Delhi": null,
							"Goa": null,
							"Gujarat": null,
							"Haryana": null,
							"Himachal Pradesh": null,
							"Jammu and Kashmir": null,
							"Jharkhand": null,
							"Karnataka": 0.24,
							"Kerala": null,
							"Lakshadweep": null,
							"Madhya Pradesh": null,
							"Maharashtra": null,
							"Manipur": null,
							"Meghalayah": null,
							"Mizoram": null,
							"Nagaland": null,
							"Orissa": null,
							"Pondicherry": null,
							"Punjab": null,
							"Rajasthan": null,
							"Sikkim": null,
							"Tamil Nadu": null,
							"Telangana": null,
							"Tripura": null,
							"Uttar Pradesh": null,
							"Uttarakhand": null,
							"West Bengal": null
						},
						{
							"category": "February",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": null,
							"Assam": null,
							"Bihar": null,
							"Chandigarh": null,
							"Chhattisgarh": null,
							"Dadra and Nagar Haveli": null,
							"Daman and Diu": null,
							"Delhi": null,
							"Goa": null,
							"Gujarat": null,
							"Haryana": null,
							"Himachal Pradesh": null,
							"Jammu and Kashmir": null,
							"Jharkhand": null,
							"Karnataka": null,
							"Kerala": null,
							"Lakshadweep": null,
							"Madhya Pradesh": null,
							"Maharashtra": null,
							"Manipur": null,
							"Meghalayah": null,
							"Mizoram": null,
							"Nagaland": null,
							"Orissa": null,
							"Pondicherry": null,
							"Punjab": null,
							"Rajasthan": null,
							"Sikkim": null,
							"Tamil Nadu": null,
							"Telangana": null,
							"Tripura": null,
							"Uttar Pradesh": null,
							"Uttarakhand": null,
							"West Bengal": null
						},
						{
							"category": "March",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": null,
							"Assam": null,
							"Bihar": null,
							"Chandigarh": null,
							"Chhattisgarh": null,
							"Dadra and Nagar Haveli": null,
							"Daman and Diu": null,
							"Delhi": null,
							"Goa": null,
							"Gujarat": null,
							"Haryana": null,
							"Himachal Pradesh": null,
							"Jammu and Kashmir": null,
							"Jharkhand": null,
							"Karnataka": null,
							"Kerala": null,
							"Lakshadweep": null,
							"Madhya Pradesh": null,
							"Maharashtra": null,
							"Manipur": null,
							"Meghalayah": null,
							"Mizoram": null,
							"Nagaland": null,
							"Orissa": null,
							"Pondicherry": null,
							"Punjab": null,
							"Rajasthan": null,
							"Sikkim": null,
							"Tamil Nadu": null,
							"Telangana": null,
							"Tripura": null,
							"Uttar Pradesh": null,
							"Uttarakhand": null,
							"West Bengal": null
						},
						{
							"category": "April",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": null,
							"Assam": null,
							"Bihar": null,
							"Chandigarh": null,
							"Chhattisgarh": null,
							"Dadra and Nagar Haveli": null,
							"Daman and Diu": null,
							"Delhi": null,
							"Goa": null,
							"Gujarat": null,
							"Haryana": null,
							"Himachal Pradesh": null,
							"Jammu and Kashmir": null,
							"Jharkhand": null,
							"Karnataka": null,
							"Kerala": null,
							"Lakshadweep": null,
							"Madhya Pradesh": null,
							"Maharashtra": null,
							"Manipur": null,
							"Meghalayah": null,
							"Mizoram": null,
							"Nagaland": null,
							"Orissa": null,
							"Pondicherry": null,
							"Punjab": null,
							"Rajasthan": null,
							"Sikkim": null,
							"Tamil Nadu": null,
							"Telangana": null,
							"Tripura": null,
							"Uttar Pradesh": null,
							"Uttarakhand": null,
							"West Bengal": null
						},
						{
							"category": "May",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": null,
							"Assam": null,
							"Bihar": null,
							"Chandigarh": null,
							"Chhattisgarh": null,
							"Dadra and Nagar Haveli": null,
							"Daman and Diu": null,
							"Delhi": null,
							"Goa": null,
							"Gujarat": null,
							"Haryana": null,
							"Himachal Pradesh": null,
							"Jammu and Kashmir": null,
							"Jharkhand": null,
							"Karnataka": null,
							"Kerala": null,
							"Lakshadweep": null,
							"Madhya Pradesh": null,
							"Maharashtra": null,
							"Manipur": null,
							"Meghalayah": null,
							"Mizoram": null,
							"Nagaland": null,
							"Orissa": null,
							"Pondicherry": null,
							"Punjab": null,
							"Rajasthan": null,
							"Sikkim": null,
							"Tamil Nadu": null,
							"Telangana": null,
							"Tripura": null,
							"Uttar Pradesh": null,
							"Uttarakhand": null,
							"West Bengal": null
						},
						{
							"category": "June",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": null,
							"Assam": null,
							"Bihar": null,
							"Chandigarh": null,
							"Chhattisgarh": null,
							"Dadra and Nagar Haveli": null,
							"Daman and Diu": null,
							"Delhi": null,
							"Goa": null,
							"Gujarat": null,
							"Haryana": null,
							"Himachal Pradesh": null,
							"Jammu and Kashmir": null,
							"Jharkhand": null,
							"Karnataka": null,
							"Kerala": null,
							"Lakshadweep": null,
							"Madhya Pradesh": null,
							"Maharashtra": null,
							"Manipur": null,
							"Meghalayah": null,
							"Mizoram": null,
							"Nagaland": null,
							"Orissa": null,
							"Pondicherry": null,
							"Punjab": null,
							"Rajasthan": null,
							"Sikkim": 579.8,
							"Tamil Nadu": null,
							"Telangana": null,
							"Tripura": 445.08,
							"Uttar Pradesh": null,
							"Uttarakhand": null,
							"West Bengal": null
						},
						{
							"category": "July",
							"Andaman and Nicobar Islands": 429.97,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": null,
							"Assam": null,
							"Bihar": null,
							"Chandigarh": null,
							"Chhattisgarh": null,
							"Dadra and Nagar Haveli": null,
							"Daman and Diu": 788.8,
							"Delhi": 139,
							"Goa": 1190.3,
							"Gujarat": 328.75,
							"Haryana": 80.20,
							"Himachal Pradesh": 268.21,
							"Jammu and Kashmir": null,
							"Jharkhand": 325.80,
							"Karnataka": null,
							"Kerala": null,
							"Lakshadweep": null,
							"Madhya Pradesh": 308.73,
							"Maharashtra": 430.04,
							"Manipur": null,
							"Meghalayah": null,
							"Mizoram": null,
							"Nagaland": null,
							"Orissa": 502.6,
							"Pondicherry": null,
							"Punjab": null,
							"Rajasthan": null,
							"Sikkim": null,
							"Tamil Nadu": null,
							"Telangana": null,
							"Tripura": null,
							"Uttar Pradesh": 188.84,
							"Uttarakhand": null,
							"West Bengal": null
						},
						{
							"category": "August",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": 628.82,
							"Assam": 442.49,
							"Bihar": 303.63,
							"Chandigarh": 334.23,
							"Chhattisgarh": null,
							"Dadra and Nagar Haveli": null,
							"Daman and Diu": null,
							"Delhi": null,
							"Goa": null,
							"Gujarat": null,
							"Haryana": null,
							"Himachal Pradesh": null,
							"Jammu and Kashmir": null,
							"Jharkhand": null,
							"Karnataka": 316.19,
							"Kerala": 732.63,
							"Lakshadweep": 466.1,
							"Madhya Pradesh": null,
							"Maharashtra": null,
							"Manipur": 272.05,
							"Meghalayah": null,
							"Mizoram": null,
							"Nagaland": 374.7,
							"Orissa": null,
							"Pondicherry": null,
							"Punjab": null,
							"Rajasthan": 205.21,
							"Sikkim": null,
							"Tamil Nadu": null,
							"Telangana": 177.7,
							"Tripura": null,
							"Uttar Pradesh": null,
							"Uttarakhand": 258.28,
							"West Bengal": 355.34
						},
						{
							"category": "September",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": null,
							"Assam": null,
							"Bihar": null,
							"Chandigarh": null,
							"Chhattisgarh": null,
							"Dadra and Nagar Haveli": null,
							"Daman and Diu": null,
							"Delhi": null,
							"Goa": null,
							"Gujarat": null,
							"Haryana": null,
							"Himachal Pradesh": null,
							"Jammu and Kashmir": 331.32,
							"Jharkhand": null,
							"Karnataka": null,
							"Kerala": null,
							"Lakshadweep": null,
							"Madhya Pradesh": null,
							"Maharashtra": null,
							"Manipur": null,
							"Meghalayah": 802.08,
							"Mizoram": 532.55,
							"Nagaland": null,
							"Orissa": null,
							"Pondicherry": null,
							"Punjab": 106.42,
							"Rajasthan": null,
							"Sikkim": null,
							"Tamil Nadu": null,
							"Telangana": null,
							"Tripura": null,
							"Uttar Pradesh": null,
							"Uttarakhand": null,
							"West Bengal": null
						},
						{
							"category": "October",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": 148.57,
							"Arunachal Pradesh": null,
							"Assam": null,
							"Bihar": null,
							"Chandigarh": null,
							"Chhattisgarh": null,
							"Dadra and Nagar Haveli": null,
							"Daman and Diu": null,
							"Delhi": null,
							"Goa": null,
							"Gujarat": null,
							"Haryana": null,
							"Himachal Pradesh": null,
							"Jammu and Kashmir": null,
							"Jharkhand": null,
							"Karnataka": null,
							"Kerala": null,
							"Lakshadweep": null,
							"Madhya Pradesh": null,
							"Maharashtra": null,
							"Manipur": null,
							"Meghalayah": null,
							"Mizoram": null,
							"Nagaland": null,
							"Orissa": null,
							"Pondicherry": 406.35,
							"Punjab": null,
							"Rajasthan": null,
							"Sikkim": null,
							"Tamil Nadu": 253.88,
							"Telangana": null,
							"Tripura": null,
							"Uttar Pradesh": null,
							"Uttarakhand": null,
							"West Bengal": null
						},
						{
							"category": "November",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": null,
							"Assam": null,
							"Bihar": null,
							"Chandigarh": null,
							"Chhattisgarh": null,
							"Dadra and Nagar Haveli": null,
							"Daman and Diu": null,
							"Delhi": null,
							"Goa": null,
							"Gujarat": null,
							"Haryana": null,
							"Himachal Pradesh": null,
							"Jammu and Kashmir": null,
							"Jharkhand": null,
							"Karnataka": null,
							"Kerala": null,
							"Lakshadweep": null,
							"Madhya Pradesh": null,
							"Maharashtra": null,
							"Manipur": null,
							"Meghalayah": null,
							"Mizoram": null,
							"Nagaland": null,
							"Orissa": null,
							"Pondicherry": null,
							"Punjab": null,
							"Rajasthan": null,
							"Sikkim": null,
							"Tamil Nadu": null,
							"Telangana": null,
							"Tripura": null,
							"Uttar Pradesh": null,
							"Uttarakhand": null,
							"West Bengal": null
						},
						{
							"category": "December",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": null,
							"Assam": null,
							"Bihar": null,
							"Chandigarh": null,
							"Chhattisgarh": null,
							"Dadra and Nagar Haveli": null,
							"Daman and Diu": null,
							"Delhi": null,
							"Goa": null,
							"Gujarat": null,
							"Haryana": null,
							"Himachal Pradesh": null,
							"Jammu and Kashmir": null,
							"Jharkhand": null,
							"Karnataka": null,
							"Kerala": null,
							"Lakshadweep": null,
							"Madhya Pradesh": null,
							"Maharashtra": null,
							"Manipur": null,
							"Meghalayah": null,
							"Mizoram": null,
							"Nagaland": null,
							"Orissa": null,
							"Pondicherry": null,
							"Punjab": null,
							"Rajasthan": null,
							"Sikkim": null,
							"Tamil Nadu": null,
							"Telangana": null,
							"Tripura": null,
							"Uttar Pradesh": null,
							"Uttarakhand": null,
							"West Bengal": null
						}
					]
				}
			);