AmCharts.makeChart("chartdiv1",
				{
					"type": "serial",
					"categoryField": "category",
					"rotate": true,
					"angle": 30,
					"depth3D": 30,
					"sequencedAnimation": false,
					"startDuration": 0.3,
					"startEffect": "elastic",
					"accessibleTitle": "",
					"handDrawThickness": 0,
					"theme": "light",
					"categoryAxis": {
						"gridPosition": "start"
					},
					"trendLines": [],
					"graphs": [
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-1",
							"title": "Andaman and Nicobar Islands",
							"type": "column",
							"valueField": "Andaman and Nicobar Islands"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-2",
							"title": "Andhra Pradesh",
							"type": "column",
							"valueField": "Andhra Pradesh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-3",
							"title": "Arunachal Pradesh",
							"type": "column",
							"valueField": "Arunachal Pradesh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-4",
							"title": "Assam",
							"type": "column",
							"valueField": "Assam"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-5",
							"title": "Bihar",
							"type": "column",
							"valueField": "Bihar"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-6",
							"title": "Chandigarh",
							"type": "column",
							"valueField": "Chandigarh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-7",
							"title": "Chhattisgarh",
							"type": "column",
							"valueField": "Chhattisgarh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-8",
							"title": "Dadra and Nagar Haveli",
							"type": "column",
							"valueField": "Dadra and Nagar Haveli"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-9",
							"title": "Daman and Diu",
							"type": "column",
							"valueField": "Daman and Diu"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-10",
							"title": "Delhi",
							"type": "column",
							"valueField": "West Bengal"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-11",
							"title": "Goa",
							"type": "column",
							"valueField": "Goa"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-12",
							"title": "Gujarat",
							"type": "column",
							"valueField": "Gujarat"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-13",
							"title": "Haryana",
							"type": "column",
							"valueField": "Haryana"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-14",
							"title": "Himachal Pradesh",
							"type": "column",
							"valueField": "Himachal Pradesh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-15",
							"title": "Jammu and Kashmir",
							"type": "column",
							"valueField": "Jammu and Kashmir"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-16",
							"title": "Jharkhand",
							"type": "column",
							"valueField": "Jharkhand"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-17",
							"title": "Karnataka",
							"type": "column",
							"valueField": "Karnataka"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-18",
							"title": "Kerala",
							"type": "column",
							"valueField": "Kerala"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-19",
							"title": "Lakshadweep",
							"type": "column",
							"valueField": "Lakshadweep"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-20",
							"title": "Madhya Pradesh",
							"type": "column",
							"valueField": "Madhya Pradesh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-21",
							"title": "Maharashtra",
							"type": "column",
							"valueField": "Maharashtra"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-22",
							"title": "Manipur",
							"type": "column",
							"valueField": "Manipur"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-23",
							"title": "Meghalayah",
							"type": "column",
							"valueField": "Meghalayah"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-24",
							"title": "Mizoram",
							"type": "column",
							"valueField": "West Bengal"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-25",
							"title": "Nagaland",
							"type": "column",
							"valueField": "Nagaland"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-26",
							"title": "Orissa",
							"type": "column",
							"valueField": "Orissa"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-27",
							"title": "Pondicherry",
							"type": "column",
							"valueField": "Pondicherry"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-28",
							"title": "Punjab",
							"type": "column",
							"valueField": "Punjab"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-29",
							"title": "Rajasthan",
							"type": "column",
							"valueField": "Rajasthan"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-30",
							"title": "Sikkim",
							"type": "column",
							"valueField": "Sikkim"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-31",
							"title": "Tamil Nadu",
							"type": "column",
							"valueField": "Tamil Nadu"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-32",
							"title": "Telangana",
							"type": "column",
							"valueField": "Telangana"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-33",
							"title": "Tripura",
							"type": "column",
							"valueField": "Tripura"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-34",
							"title": "Uttar Pradesh",
							"type": "column",
							"valueField": "Uttar Pradesh"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-35",
							"title": "Uttarakhand",
							"type": "column",
							"valueField": "Uttarakhand"
						},
						{
							"balloonText": "[[title]] in [[category]]:[[value]]mm",
							"fillAlphas": 1,
							"id": "AmGraph-36",
							"title": "West Bengal",
							"type": "column",
							"valueField": "West Bengal"
						}
					],
					"guides": [],
					"valueAxes": [
						{
							"id": "ValueAxis-1",
							"stackType": "regular",
							"title": ""
						}
					],
					"allLabels": [
						{
							"id": "Label-1"
						}
					],
					"balloon": {},
					"legend": {
						"enabled": true,
						"useGraphSettings": true
					},
					"titles": [
						{
							"id": "Title-1",
							"size": 15,
							"text": ""
						}
					],
					"dataProvider": [
						{
							"category": "January",
							"Andaman and Nicobar Islands": "",
							"Andhra Pradesh": 5,
							"Arunachal Pradesh": 46,
							"Assam": "",
							"Bihar": "",
							"Chandigarh": "",
							"Chhattisgarh": "",
							"Dadra and Nagar Haveli": "",
							"Daman and Diu": "",
							"Delhi": "",
							"Goa": "",
							"Gujarat": "",
							"Haryana": "",
							"Himachal Pradesh": "",
							"Jammu and Kashmir": "",
							"Jharkhand": "",
							"Karnataka": "",
							"Kerala": "",
							"Lakshadweep": "",
							"Madhya Pradesh": "",
							"Maharashtra": "",
							"Manipur": "",
							"Meghalayah": "",
							"Mizoram": "",
							"Nagaland": "",
							"Orissa": "",
							"Pondicherry": "",
							"Punjab": "",
							"Rajasthan": "",
							"Sikkim": "",
							"Tamil Nadu": "",
							"Telangana": "",
							"Tripura": "",
							"Uttar Pradesh": "",
							"Uttarakhand": "",
							"West Bengal": ""
						},
						{
							"category": "February",
							"Andaman and Nicobar Islands": "",
							"Andhra Pradesh": "",
							"Arunachal Pradesh": "",
							"Assam": "",
							"Bihar": "",
							"Chandigarh": "",
							"Chhattisgarh": "",
							"Dadra and Nagar Haveli": "",
							"Daman and Diu": 94,
							"Delhi": "",
							"Goa": "",
							"Gujarat": "",
							"Haryana": "",
							"Himachal Pradesh": "",
							"Jammu and Kashmir": 88,
							"Jharkhand": "",
							"Karnataka": "",
							"Kerala": "",
							"Lakshadweep": "",
							"Madhya Pradesh": "",
							"Maharashtra": "",
							"Manipur": 96,
							"Meghalayah": "",
							"Mizoram": "",
							"Nagaland": "",
							"Orissa": "",
							"Pondicherry": "",
							"Punjab": "",
							"Rajasthan": "",
							"Sikkim": "",
							"Tamil Nadu": "",
							"Telangana": "",
							"Tripura": "",
							"Uttar Pradesh": "",
							"Uttarakhand": "",
							"West Bengal": ""
						},
						{
							"category": "March",
							"Andaman and Nicobar Islands": 2,
							"Andhra Pradesh": "",
							"Arunachal Pradesh": "",
							"Assam": "",
							"Bihar": "",
							"Chandigarh": "",
							"Chhattisgarh": "",
							"Dadra and Nagar Haveli": "",
							"Daman and Diu": "",
							"Delhi": "",
							"Goa": "",
							"Gujarat": "",
							"Haryana": "",
							"Himachal Pradesh": "",
							"Jammu and Kashmir": "",
							"Jharkhand": "",
							"Karnataka": "",
							"Kerala": "",
							"Lakshadweep": "",
							"Madhya Pradesh": "",
							"Maharashtra": "",
							"Manipur": "",
							"Meghalayah": "",
							"Mizoram": "",
							"Nagaland": "",
							"Orissa": "",
							"Pondicherry": "",
							"Punjab": "",
							"Rajasthan": "",
							"Sikkim": "",
							"Tamil Nadu": "",
							"Telangana": "",
							"Tripura": "",
							"Uttar Pradesh": "",
							"Uttarakhand": "",
							"West Bengal": ""
						},
						{
							"category": "April",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": "",
							"Assam": "",
							"Bihar": 72,
							"Chandigarh": "",
							"Chhattisgarh": "",
							"Dadra and Nagar Haveli": "",
							"Daman and Diu": "",
							"Delhi": "",
							"Goa": "",
							"Gujarat": "",
							"Haryana": "",
							"Himachal Pradesh": "",
							"Jammu and Kashmir": "",
							"Jharkhand": "",
							"Karnataka": "",
							"Kerala": "",
							"Lakshadweep": "",
							"Madhya Pradesh": "",
							"Maharashtra": "",
							"Manipur": "",
							"Meghalayah": "",
							"Mizoram": "",
							"Nagaland": "",
							"Orissa": "",
							"Pondicherry": "",
							"Punjab": 40,
							"Rajasthan": "",
							"Sikkim": "",
							"Tamil Nadu": "",
							"Telangana": "",
							"Tripura": "",
							"Uttar Pradesh": 38,
							"Uttarakhand": "",
							"West Bengal": ""
						},
						{
							"category": "May",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": "",
							"Assam": "",
							"Bihar": "",
							"Chandigarh": "",
							"Chhattisgarh": "",
							"Dadra and Nagar Haveli": 89,
							"Daman and Diu": "",
							"Delhi": "",
							"Goa": "",
							"Gujarat": "",
							"Haryana": "",
							"Himachal Pradesh": "",
							"Jammu and Kashmir": "",
							"Jharkhand": "",
							"Karnataka": "",
							"Kerala": "",
							"Lakshadweep": 12,
							"Madhya Pradesh": "",
							"Maharashtra": 25,
							"Manipur": "",
							"Meghalayah": "",
							"Mizoram": "",
							"Nagaland": "",
							"Orissa": "",
							"Pondicherry": 79,
							"Punjab": "",
							"Rajasthan": "",
							"Sikkim": "",
							"Tamil Nadu": 37,
							"Telangana": "",
							"Tripura": "",
							"Uttar Pradesh": "",
							"Uttarakhand": "",
							"West Bengal": ""
						},
						{
							"category": "June",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": "",
							"Assam": "",
							"Bihar": "",
							"Chandigarh": "",
							"Chhattisgarh": "",
							"Dadra and Nagar Haveli": "",
							"Daman and Diu": "",
							"Delhi": "",
							"Goa": 93,
							"Gujarat": "",
							"Haryana": "",
							"Himachal Pradesh": "",
							"Jammu and Kashmir": "",
							"Jharkhand": "",
							"Karnataka": "",
							"Kerala": "",
							"Lakshadweep": "",
							"Madhya Pradesh": "",
							"Maharashtra": "",
							"Manipur": "",
							"Meghalayah": "",
							"Mizoram": 44,
							"Nagaland": 31,
							"Orissa": "",
							"Pondicherry": "",
							"Punjab": "",
							"Rajasthan": 64,
							"Sikkim": "",
							"Tamil Nadu": "",
							"Telangana": "",
							"Tripura": "",
							"Uttar Pradesh": "",
							"Uttarakhand": 41,
							"West Bengal": ""
						},
						{
							"category": "July",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": "",
							"Assam": "",
							"Bihar": "",
							"Chandigarh": "",
							"Chhattisgarh": "",
							"Dadra and Nagar Haveli": "",
							"Daman and Diu": "",
							"Delhi": "",
							"Goa": "",
							"Gujarat": 83,
							"Haryana": 85,
							"Himachal Pradesh": "",
							"Jammu and Kashmir": "",
							"Jharkhand": "",
							"Karnataka": 86,
							"Kerala": "",
							"Lakshadweep": "",
							"Madhya Pradesh": "",
							"Maharashtra": "",
							"Manipur": "",
							"Meghalayah": "",
							"Mizoram": "",
							"Nagaland": "",
							"Orissa": "",
							"Pondicherry": "",
							"Punjab": "",
							"Rajasthan": "",
							"Sikkim": "",
							"Tamil Nadu": "",
							"Telangana": "",
							"Tripura": 76,
							"Uttar Pradesh": "",
							"Uttarakhand": "",
							"West Bengal": ""
						},
						{
							"category": "August",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": "",
							"Assam": "",
							"Bihar": "",
							"Chandigarh": "",
							"Chhattisgarh": "",
							"Dadra and Nagar Haveli": "",
							"Daman and Diu": "",
							"Delhi": 87,
							"Goa": "",
							"Gujarat": "",
							"Haryana": "",
							"Himachal Pradesh": "",
							"Jammu and Kashmir": "",
							"Jharkhand": "",
							"Karnataka": "",
							"Kerala": 64,
							"Lakshadweep": "",
							"Madhya Pradesh": "",
							"Maharashtra": "",
							"Manipur": "",
							"Meghalayah": 13,
							"Mizoram": "",
							"Nagaland": "",
							"Orissa": "",
							"Pondicherry": "",
							"Punjab": "",
							"Rajasthan": "",
							"Sikkim": "",
							"Tamil Nadu": "",
							"Telangana": 81,
							"Tripura": "",
							"Uttar Pradesh": "",
							"Uttarakhand": "",
							"West Bengal": ""
						},
						{
							"category": "September",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": "",
							"Assam": "",
							"Bihar": "",
							"Chandigarh": "",
							"Chhattisgarh": "",
							"Dadra and Nagar Haveli": "",
							"Daman and Diu": "",
							"Delhi": "",
							"Goa": "",
							"Gujarat": "",
							"Haryana": "",
							"Himachal Pradesh": "",
							"Jammu and Kashmir": "",
							"Jharkhand": "",
							"Karnataka": "",
							"Kerala": "",
							"Lakshadweep": "",
							"Madhya Pradesh": "",
							"Maharashtra": "",
							"Manipur": "",
							"Meghalayah": "",
							"Mizoram": "",
							"Nagaland": "",
							"Orissa": 18,
							"Pondicherry": "",
							"Punjab": "",
							"Rajasthan": "",
							"Sikkim": 63,
							"Tamil Nadu": "",
							"Telangana": "",
							"Tripura": "",
							"Uttar Pradesh": "",
							"Uttarakhand": "",
							"West Bengal": 73
						},
						{
							"category": "October",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": "",
							"Assam": "",
							"Bihar": "",
							"Chandigarh": "",
							"Chhattisgarh": "",
							"Dadra and Nagar Haveli": "",
							"Daman and Diu": "",
							"Delhi": "",
							"Goa": "",
							"Gujarat": "",
							"Haryana": "",
							"Himachal Pradesh": "",
							"Jammu and Kashmir": "",
							"Jharkhand": 97,
							"Karnataka": "",
							"Kerala": "",
							"Lakshadweep": "",
							"Madhya Pradesh": 96,
							"Maharashtra": "",
							"Manipur": "",
							"Meghalayah": "",
							"Mizoram": "",
							"Nagaland": "",
							"Orissa": "",
							"Pondicherry": "",
							"Punjab": "",
							"Rajasthan": "",
							"Sikkim": "",
							"Tamil Nadu": "",
							"Telangana": "",
							"Tripura": "",
							"Uttar Pradesh": "",
							"Uttarakhand": "",
							"West Bengal": ""
						},
						{
							"category": "November",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": "",
							"Assam": 7,
							"Bihar": "",
							"Chandigarh": 59,
							"Chhattisgarh": 98,
							"Dadra and Nagar Haveli": "",
							"Daman and Diu": "",
							"Delhi": "",
							"Goa": "",
							"Gujarat": "",
							"Haryana": "",
							"Himachal Pradesh": 98,
							"Jammu and Kashmir": "",
							"Jharkhand": "",
							"Karnataka": "",
							"Kerala": "",
							"Lakshadweep": "",
							"Madhya Pradesh": "",
							"Maharashtra": "",
							"Manipur": "",
							"Meghalayah": "",
							"Mizoram": "",
							"Nagaland": "",
							"Orissa": "",
							"Pondicherry": "",
							"Punjab": "",
							"Rajasthan": "",
							"Sikkim": "",
							"Tamil Nadu": "",
							"Telangana": "",
							"Tripura": "",
							"Uttar Pradesh": "",
							"Uttarakhand": "",
							"West Bengal": ""
						},
						{
							"category": "December",
							"Andaman and Nicobar Islands": null,
							"Andhra Pradesh": null,
							"Arunachal Pradesh": "",
							"Assam": "",
							"Bihar": "",
							"Chandigarh": "",
							"Chhattisgarh": "",
							"Dadra and Nagar Haveli": "",
							"Daman and Diu": "",
							"Delhi": "",
							"Goa": "",
							"Gujarat": "",
							"Haryana": "",
							"Himachal Pradesh": "",
							"Jammu and Kashmir": "",
							"Jharkhand": "",
							"Karnataka": "",
							"Kerala": "",
							"Lakshadweep": "",
							"Madhya Pradesh": "",
							"Maharashtra": "",
							"Manipur": "",
							"Meghalayah": "",
							"Mizoram": "",
							"Nagaland": "",
							"Orissa": "",
							"Pondicherry": "",
							"Punjab": "",
							"Rajasthan": "",
							"Sikkim": "",
							"Tamil Nadu": "",
							"Telangana": "",
							"Tripura": "",
							"Uttar Pradesh": "",
							"Uttarakhand": "",
							"West Bengal": ""
						}
					]
				}
			);